workspace:
  base: /go
  path: src/github.com/karantin2020/jwt-auth

pipeline:
  test1.8:
    image: golang:1.8.3-alpine
    commands:
      - cd jwt
      - go test -v
      
  test1.9:
    image: golang:1.9.0-alpine3.6
    commands:
      - cd jwt
      - go test -v
