workspace:
  base: /go
  path: src/github.com/karantin2020/jwt-auth/jwt

pipeline:
  test:
    image: golang:1.8.3-alpine
    commands:
      - apk update
      - apk add git
      - ls
      - go test -v